In [161]:
import numpy as np

#1. Create a null array of size 10 but the fifth value which is 1
size1=10
x1=np.empty(size1)
x1[4]=1

print (x1)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [160]:
#2. Reverse a above created array (first element becomes last)
x2= x1[::-1]
print ('Reversed x1 is %s\n'%x2)

Reversed x1 is [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



In [148]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
Max_N=8+1
Len_R=3
Len_C=3
x3=np.random.randint(0,8, (Len_R, Len_C))
print("The created matrix x3 is: \n")
print (x3)

x4 = np.arange(Max_N). reshape(Len_R, Len_C)
print("\nThe created matrix x4 is: \n")
print (x4)

The created matrix x3 is: 

[[6 0 4]
 [6 4 3]
 [2 2 6]]

The created matrix x4 is: 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [149]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
x5=np.array([1,2,0,0,4,0])
for i in x5:
    Ind=np.where(x5==i)
    print('Elements with value %s'%i,' exists at following indices %s\n'%Ind[0])

Elements with value 1  exists at following indices [0]

Elements with value 2  exists at following indices [1]

Elements with value 0  exists at following indices [2 3 5]

Elements with value 0  exists at following indices [2 3 5]

Elements with value 4  exists at following indices [4]

Elements with value 0  exists at following indices [2 3 5]



In [150]:
#5. Create a 3x3x3 array with random values
Len_1=3
Len_2=3
Len_3=3
x6=np.random.random(size= (Len_1, Len_2, Len_3))
print("The created matrix x6 is: \n")
print (x6)

The created matrix x6 is: 

[[[0.38756787 0.90801788 0.10617466]
  [0.25759677 0.1658186  0.66899201]
  [0.78975519 0.42292407 0.53497467]]

 [[0.09385981 0.70157531 0.49388879]
  [0.52536308 0.06709341 0.70223237]
  [0.66027511 0.29917681 0.18130708]]

 [[0.62040652 0.92495319 0.04686256]
  [0.48701241 0.90095825 0.83376899]
  [0.4203045  0.26695128 0.30570845]]]


In [151]:
#6. Create a 10x10 array with random values and find the minimum and maximum values
Len_R=10
Len_C=10
x7=np.random.random(size= (Len_R, Len_C))
min_ele=np.min(x7)
max_ele=np.max(x7)
print ('The whole matrix is\n',x7)
print ('\nThe minimal element in x7 is %s\n'%min_ele)
print ('The maximal element in x7 is %s\n'%max_ele)

The whole matrix is
 [[0.51678487 0.01625373 0.20624748 0.08802779 0.08512195 0.97500283
  0.74887194 0.32633903 0.57041221 0.14927964]
 [0.34619754 0.07113958 0.10164333 0.79995315 0.20086069 0.88949948
  0.86694646 0.74460484 0.49774418 0.99645365]
 [0.00834154 0.67292964 0.72657421 0.32088321 0.32276426 0.85474997
  0.4914037  0.72734739 0.15057895 0.64841882]
 [0.20461078 0.44736085 0.83745763 0.74732987 0.04238325 0.80159034
  0.6753808  0.16484361 0.46937412 0.83145331]
 [0.45359974 0.64616217 0.83892029 0.43421541 0.5227156  0.76427239
  0.58597545 0.03385274 0.78691617 0.26275835]
 [0.64845918 0.17326736 0.66839653 0.41232248 0.68248147 0.943677
  0.60034338 0.96132109 0.09744955 0.39513167]
 [0.41966436 0.93505619 0.18804541 0.74385876 0.61198942 0.99123454
  0.86833152 0.65363271 0.12233938 0.54562074]
 [0.29401141 0.64605763 0.79099944 0.63188968 0.06882587 0.12185188
  0.16409262 0.30904117 0.41012544 0.54414325]
 [0.60872433 0.43262011 0.83103478 0.74789087 0.07826084 0.78

In [152]:
#7. Create a random vector of size 30 and find the mean value
x8=np.random.randint(low=0, high=99, size=(30,))
print ('The matrix  is \n%s\n'%x8)
mean_x8=np.mean(x8)
print ('\nThe average of x8 is %s\n'%mean_x8)

The matrix  is 
[12 80 17 51 85  3 58 26 25 64 82 34 50 73 50 78  3 51 96 31 14 16 98 24
 50 80 36 53 23  3]


The average of x8 is 45.53333333333333



In [153]:
#8. Create a 2d array with 1 on the border and 0 inside
Len_R=10
Len_C=10
x9=np.zeros(shape=(Len_R, Len_C))
x9[0]=np.ones(shape=(Len_C))
x9[:,0]=np.ones(shape=(Len_R,))
#x9[-1]=np.ones(shape=(Len_C))
x9[-1]=1
#x9[:,-1]=np.ones(shape=(Len_R,))
x9[:,-1]=1
print ('The matrix  is \n%s\n'%x9)

The matrix  is 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



In [154]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
Len_R1=5
Len_C1=3
Len_R2=3
Len_C2=2
x10_1=np.random.randint(low=0, high=50, size=(Len_R1, Len_C1))
x10_2=np.random.randint(low=51, high=99, size=(Len_R2, Len_C2))
x10=np.dot(x10_1, x10_2)
print ('Matrix 1 is \n%s\n'%x10_1)
print ('Matrix 2 is \n%s\n'%x10_2)
print ('Matrix product is \n%s\n'%x10)
print ('---------------\n')


Matrix 1 is 
[[29 27 15]
 [36 16 36]
 [ 5 25 43]
 [ 9 35  6]
 [29 47 38]]

Matrix 2 is 
[[91 65]
 [59 60]
 [54 51]]

Matrix product is 
[[5042 4270]
 [6164 5136]
 [4252 4018]
 [3208 2991]
 [7464 6643]]

---------------



In [93]:
#10. Extract the integer part of a random array
Len=10
x11= 100 * np.random.random(size=(Len,)) 
x11_1=np.zeros(shape=(Len,))
print ('Original matrix is : \n%s\n'%x11)
for i in range(Len):
    x11_1[i]=int(x11[i])
print ('Integer part of the original matrix is : \n%s\n'%x11_1)

Original matrix is : 
[30.20406938 57.53119316 82.17026868 69.73065603 12.38914078 25.15610161
 41.03489076 59.0419925   5.78621549 53.37932601]

Integer part of the original matrix is : 
[30. 57. 82. 69. 12. 25. 41. 59.  5. 53.]



In [102]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4
Len_R1=5
Len_C1=5
x12=np.random.randint(low=0, high=5, size=(Len_R1, Len_C1))
print(x12)

[[0 4 2 4 0]
 [4 2 3 1 1]
 [0 1 1 1 4]
 [1 2 0 0 1]
 [1 3 2 3 3]]


In [107]:
#12.  Create a random vector of size 10 and sort it
Len_R=10
x13=np.random.randint(low=0, high=Len_R, size=(Len_R, ))
print ('Original matrix is : \n%s\n'%x13)
x13_1=np.sort(x13)
print ('The sorted matrix is : \n%s\n'%x13_1)

Original matrix is : 
[7 4 0 3 5 8 4 3 3 6]

The sorted matrix is : 
[0 3 3 3 4 4 5 6 7 8]



In [108]:
#13. Consider two random array A anb B, check if they are equal.
Len_R=10
x14_1=np.random.randint(low=0, high=Len_R, size=(Len_R, ))
x14_2=np.random.randint(low=0, high=Len_R, size=(Len_R, ))
print ('Matrix A is : \n%s\n'%x14_1)
print ('Matrix A is : \n%s\n'%x14_2)
if np.array_equal(x14_1, x14_2):
    print ('\nThe two random array are equal\n')
else:
    print ('\nThe two random array are NOT equal\n')

Matrix A is : 
[8 0 3 7 4 1 1 4 3 2]

Matrix A is : 
[5 0 6 1 6 3 3 0 1 6]


The two random array are NOT equal



In [112]:
#14. How to tell if a given 2D array has null columns?
Len_R1=10
Len_C1=10
x15=np.random.randint(low=0, high=5, size=(Len_R1, Len_C1))
print ('Matrix is : \n%s\n'%x15)
if ((~x15.any(axis=0)).any()):
    print('There are null column(s)')
else:
    print('There isn\'t any null column(s)')

Matrix is : 
[[0 1 0 2 0 2 3 2 0 4]
 [1 4 2 1 0 2 1 3 4 2]
 [1 0 2 3 4 4 3 1 1 4]
 [3 3 1 4 0 4 1 3 3 2]
 [0 1 0 3 3 2 1 3 2 3]
 [4 0 1 3 4 1 4 0 4 0]
 [4 1 3 4 0 3 3 1 1 3]
 [2 3 2 3 2 3 4 4 1 3]
 [1 0 2 2 3 1 1 1 2 3]
 [3 4 1 0 0 1 3 2 3 1]]

There isn't any null column(s)


In [127]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?
Len_1=5
Len_2=5
Len_3=5
Len_4=5
x15=np.random.randint(low=0, high=5, size=(Len_1, Len_2, Len_3, Len_4))
sum=np.zeros(shape=(Len_1,Len_2))
for i1 in range(Len_1):
    for i2 in range(Len_2):
         for i3 in range(Len_3):
                 for i4 in range(Len_4):
                        sum[i1][i2]=sum[i1][i2]+x15[i1][i2][i3][i4]
         print('Sum over the last two axis for %s'%i1, ' %s'%i2, ' is: %s\n'%sum[i1][i2])
        

Sum over the last two axis for 0  0  is: 52.0

Sum over the last two axis for 0  1  is: 53.0

Sum over the last two axis for 0  2  is: 54.0

Sum over the last two axis for 0  3  is: 45.0

Sum over the last two axis for 0  4  is: 40.0

Sum over the last two axis for 1  0  is: 53.0

Sum over the last two axis for 1  1  is: 50.0

Sum over the last two axis for 1  2  is: 54.0

Sum over the last two axis for 1  3  is: 57.0

Sum over the last two axis for 1  4  is: 53.0

Sum over the last two axis for 2  0  is: 51.0

Sum over the last two axis for 2  1  is: 46.0

Sum over the last two axis for 2  2  is: 56.0

Sum over the last two axis for 2  3  is: 59.0

Sum over the last two axis for 2  4  is: 48.0

Sum over the last two axis for 3  0  is: 44.0

Sum over the last two axis for 3  1  is: 57.0

Sum over the last two axis for 3  2  is: 42.0

Sum over the last two axis for 3  3  is: 54.0

Sum over the last two axis for 3  4  is: 44.0

Sum over the last two axis for 4  0  is: 49.0

Sum over the 

In [136]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#Question: I'm not sure if this is right. I tried different things, but taking the outer product of
#arrays with non-equal dimensions seems to work. I did not find a solution in the videos or in the notebook, so
#I tried to find something online.
Len_1=5
Len_2=5
Len_3=3
x16_1=np.random.randint(low=0, high=75, size=(Len_1, Len_2, Len_3))
x16_2=np.random.randint(low=76, high=100, size=(Len_1, Len_2))
print('The fist Matrix is \n%s'%x16_1)
print('\nThe second Matrix is \n%s'%x16_2)
x16=np.outer(x16_1, x16_2)
print('\nThe result Matrix is \n%s'%x16)

The fist Matrix is 
[[[39 18 31]
  [39  2 63]
  [63 71 66]
  [48 62 35]
  [57 30 54]]

 [[60 68 30]
  [69 33 70]
  [37 48 19]
  [10 48 11]
  [34 56 39]]

 [[39 66  4]
  [28  4 42]
  [ 4 61 67]
  [56  6 33]
  [42 28 28]]

 [[56 62 68]
  [35 42 71]
  [19 23 34]
  [27 15 36]
  [56 70 26]]

 [[67 49 26]
  [47 27 30]
  [22 16 55]
  [51  2  5]
  [29 17 73]]]

The second Matrix is 
[[96 98 76 88 97]
 [94 99 83 96 89]
 [83 92 92 86 77]
 [95 79 87 97 86]
 [79 91 91 89 95]]

The result Matrix is 
[[3744 3822 2964 ... 3549 3471 3705]
 [1728 1764 1368 ... 1638 1602 1710]
 [2976 3038 2356 ... 2821 2759 2945]
 ...
 [2784 2842 2204 ... 2639 2581 2755]
 [1632 1666 1292 ... 1547 1513 1615]
 [7008 7154 5548 ... 6643 6497 6935]]


In [164]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
#CONFUSED: Outside of my understanding from the lectures. Sorry. I can make the matrix but not sure how 
#to get the 'blocks'
Len_1=10
Len_2=10
x17_t=np.zeros(shape=(3, 3))
x17=np.random.randint(low=0, high=100, size=(Len_1, Len_2))
print('The original Matrix is \n%s'%x17)
count=0
for i in range(Len_1-2):
    for j in range(Len_2-2):
        count=count+1
print('\nThere are %s'%count, ' 3x3 blocks')        



The original Matrix is 
[[61 64 55 62  0 22  2 19 30 27]
 [36 46 28 54 82 34  2 95 71 92]
 [99 87 39 94 36 87 55 30 73 86]
 [92 52 71 88 85 29 16 65  9 29]
 [14  3 10 53 58  0 78  5  0 81]
 [59  1 96  7 34 67 50 54 34  8]
 [19 28 60 33 77 17 59 91 54 27]
 [ 8  8 44 14 75 36 32 74 59 81]
 [99 83 85 79 12 35 27 33 21 98]
 [63 45 40 36 32 92 89 65 39 30]]

There are 64  3x3 blocks


In [166]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Len_1=16
Len_2=16
x18_t=np.zeros(shape=(4, 4))
x18=np.random.randint(low=0, high=300, size=(Len_1, Len_2))
print('The original Matrix is \n%s'%x18)

for i in range(4):
    for j in range(4):
        x18_t[i][j]=x18[i][j]

count=1
for i in (1,Len_1-3):
    for j in (1,Len_2-3):
        count=count+1
        x18_t[i%4][j%4]= x18_t[i%4][j%4]+x18[i][j]
print('\nThere are %s'%count, ' 4x4 blocks') 
print('The sum of the 4x4 matrix is \n%s'%x18_t)

The original Matrix is 
[[267  96 251  25 225  33 243 205 117 118   6 194  30 151 142 144]
 [150 185 222  70 123  45 163 217 217  41 264 200  80  10 106 165]
 [ 34 124 110  43  37 202  35  64 278 262  67  10  74 143  25 270]
 [141 198 260   6  64 248 173 274  23 202  98 241 275  21 103  69]
 [ 21 243 220 235   5  67 294  50 222 110 115  74 183 276  71 239]
 [107  70 160  92 269  12 256  65 128 277 213 263 213 107 258  35]
 [121   8 288 132  47 123 235 138 280 204  81  49  26 274 107 213]
 [ 80  64  15  35  14 143 118   4 273 166  72 281 214  89 207 251]
 [270 194 265 134 279 115  46 215 130 141 266  66 207  81  41 266]
 [221 261   0 120  14 124  86  26 126   0 127  59 110 265 210 150]
 [  3 104  76 261 254   5 185 268  72  53  95 258 267 161 237  43]
 [283 220 197  32 223 259 150  81 221 169 280 249 230  30 200 146]
 [113  89 204 151 279 204 264  38  96 250 262 276 218 117 105  63]
 [151  83 257 210 264 101  86 138 115 249  42  15 135 276 226  86]
 [151 254 191 156 239  76 102 124  49 

In [172]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences
from scipy.stats import ttest_ind
from scipy.stats import t
x19_1 = np.random.randn(1000)
x19_2 = np.random.randn(1000)
t_stat, p = ttest_ind(x19_1, x19_2)
print(f't={t_stat}, p={p}')


t=-0.7651603661973713, p=0.44426642582789555
